services:
  - type: web
    name: my-telegram-bot
    env: python
    plan: free
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "python main.py"
    pythonVersion: 3.10.13
