services:
  - type: web
    name: my-telegram-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    runtime: python3
    pythonVersion: 3.10.13
